
version: '2.3'

services:

  gogs:
    container_name: gogs2
    image: gogs/gogs:latest
    # hostname: gogs.chris-perkins.uk
    ports:
      - "2222:2222"
      - "3000:3000"
      - "8443:8443"
    volumes:
      - type: bind
        source: ./data
        target: /data

      #- type: volume
      #  source: gogs_data
      #  target: /data
    networks:
      - gogs

  # postgres:
  #   image: postgres:10.5-alpine
  #   volumes:
  #     - type: volume
  #       source: postgres_data
  #       target: /var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=admin
  #   # - POSTGRES_USER=postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - gogsnet

networks:
  gogs:

# volumes:
#   postgres_data:
#   #googs_data