
version: '2.3'

services:

  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    ports:
      - "2222:22"
      - "3000:3000"
      - "8443:8443"
    volumes:
      - type: bind
        source: ./data
        target: /data

    networks:
      - gogs

networks:
  gogs:
