- hosts: "{{ hosts | default('local') }}"
  gather_facts: true
  tasks:
    - name: 安装基础软件包
      yum:
        name:
          - "epel-release"
          - "wget"
          - "curl"
          - "git"
          - "unzip"
          - "net-tools"
        state: latest

