---
- name: 如果 {{ gogs_data_dir }} 不存在则创建
  file:
    path: "{{ gogs_data_dir }}"
    state: directory
    mode: '0710'
    owner: 1000
    group: 1000
    recurse: yes

# Copy Docker Compose file and Gogs config template
- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: "{{ gogs_dir }}/docker-compose.yml"

- name: Run
  shell: docker compose up -d
  args:
    chdir: "{{ gogs_dir }}"

# - name: Copy Gogs config template
#   template:
#     src: app.ini.j2
#     dest: "{{ gogs_data_dir }}/app.ini"
#     mode: '0640'
