services:
  jenkins:
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    user: "root"
    image: jenkins/jenkins:lts
    restart: always
    environment:
      - "JAVA_OPTS=-Duser.timezone=Asia/Shanghai"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    networks:
      - jenkins

networks:
  jenkins: